### ISSUE TITLE
Wrong font

### ISSUE THREAD

**Issue by ivancucer** [charliecm/figma-fix-sf#1]
Hello @charliecm 

Seems like I'm a first bug reporter here 🎉
So when I apply the plugin, it changes the font from`SF Pro Display` to `SF Pro Text`

Any ideas why?

Thanks,
Ivan

**Comment by charliecm** [comment]
According to [Apple's Human Interface Guideline](https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/typography/#choosing-fonts-to-enhance-your-app), iOS will use `SF Pro Display` for texts 20 pt or larger and `SF Pro Text` otherwise:

![](https://user-images.githubusercontent.com/2857980/79695103-9b5c2a00-8229-11ea-9b99-a70f388d330b.png)

Hence, this plugin automates that for you. Hope that makes sense 🙂

**Comment by ivancucer** [comment]
Oh, I see, my bad. Thanks for clarification 👍
